import React from 'react'

export default function StoriesInfo() {
  const handleNext = () => {
    // Handle navigation to next page
    console.log("Proceeding to next step")
  }

  return (
    <div style={{
      minHeight: '100vh',
      backgroundColor: '#fdf7f2',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '1rem',
      fontFamily: 'Inter, system-ui, sans-serif'
    }}>
      <div style={{
        width: '100%',
        maxWidth: '40rem',
        backgroundColor: 'white',
        borderRadius: '0.5rem',
        boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        overflow: 'hidden'
      }}>
        <div style={{ padding: '2rem' }}>
          <h2 style={{
            fontSize: '2rem',
            fontWeight: '600',
            color: '#333',
            marginBottom: '1.5rem',
            textAlign: 'center',
          }}>
            Stories
          </h2>
          <p style={{
            fontSize: '1rem',
            color: '#4B5563',
            marginBottom: '1rem',
            lineHeight: '1.5'
          }}>
            In this part, wed love for you to share a few stories for the speech. Make sure each story has a beginning, middle, and end.
          </p>
          <p style={{
            fontSize: '1rem',
            color: '#4B5563',
            marginBottom: '1rem',
            lineHeight: '1.5'
          }}>
            Providing detailed stories or memories can greatly enhance the quality of the speech generated by the AI. The more context you provide, the more personalized and meaningful the speech will be!
          </p>
          <p style={{
            fontSize: '1rem',
            color: '#4B5563',
            marginBottom: '1.5rem',
            lineHeight: '1.5'
          }}>
            Just remember not to talk about the physical features of the person getting married, stories about old relationships, or any inappropriate tales.
          </p>
        </div>
        <div style={{
          backgroundColor: '#2d4739',
          color: 'white',
          padding: '1rem',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <button style={{
            backgroundColor: 'transparent',
            border: 'none',
            color: 'white',
            cursor: 'pointer',
            fontSize: '0.875rem',
            padding: '0.5rem 1rem',
            display: 'flex',
            alignItems: 'center'
          }}>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: '0.5rem' }}>
              <line x1="19" y1="12" x2="5" y2="12"></line>
              <polyline points="12 19 5 12 12 5"></polyline>
            </svg>
            PREVIOUS
          </button>
          <button
            onClick={handleNext}
            style={{
              backgroundColor: 'transparent',
              border: 'none',
              color: 'white',
              cursor: 'pointer',
              fontSize: '0.875rem',
              padding: '0.5rem 1rem',
              display: 'flex',
              alignItems: 'center'
            }}
          >
            NEXT
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginLeft: '0.5rem' }}>
              <line x1="5" y1="12" x2="19" y2="12"></line>
              <polyline points="12 5 19 12 12 19"></polyline>
            </svg>
          </button>
        </div>
      </div>
    </div>
  )
}